### ISSUE TITLE
Feature Request - Button location

### ISSUE THREAD

**Issue by theone11** [dlandon/file.activity#2]
Can you add an option/setting to have the buttons always be on top?
![image](https://user-images.githubusercontent.com/3348953/148550842-a53e1890-44ff-44eb-baf4-b152a25ae735.png)

This is because when the log gets log need to scroll to the end to find the buttons.

**Comment by dlandon** [comment]
I'd rather not add a configurable option.  I'm discussing this with Limetech because it really applies to all log pages in Unraid, and anything I do should be done in a standard way with the rest of Unraid.  For the moment I'll hold on this to see what the devs at Limetech and I can come up with.

**Comment by dlandon** [comment]
I'm told there is a setting in the Settings->Display Settings called 'Listing height:'.  Set it to 'fixed' and the buttons will always show on the page at the bottom.

**Comment by theone11** [comment]
Thanks that indeed helps.

**Comment by dlandon** [comment]
It's not documented very well as I didn't even know it was there or what it did.  I'm working with Limetech to get the help on that page improved since there is really none.
